### PR TITLE
fix: escape _

### PR DESCRIPTION
**Pull request by caarlos0**
refs #7

### CODE REVIEW

**Comment by metalmatze** [comment]
Thank you!

**Comment by caarlos0** [comment]
thanks

just realized I ref the wrong issue, should be #21

**Comment by caarlos0** [comment]
if you could also release a new version, that would be awesome :) 

Thanks for the great project...

**Comment by metalmatze** [comment]
I might be able to release a new bug fix release in the next days. I'm on the road right now.
If I don't please come back to me again. 😎

**Comment by metalmatze** [comment]
Version 0.3.1 is out:
https://github.com/metalmatze/alertmanager-bot/releases/tag/0.3.1

**Comment by caarlos0** [comment]
thanks!

**Pull request merged**
