### PR TITLE
Support description annotation which is used by newer alerts

### PR DESCRIPTION
**Pull request by runningman84**
I am not 100% sure if this works please double check...

The current template lacks description support and the duration could also be hidden if there is no end date? In my tests it is "-" until the event is solved.

### CODE REVIEW

**Comment by metalmatze** [comment]
Thanks for taking a look at this. Maybe for completeness we could also add summary too?

It was summary & description in Prometheus for a fair amount of time then we pivoted towards simply using message, as summary and description more than often were super similar.

**Comment by runningman84** [comment]
I have added the summary too...

Btw. do you know why the duration is - until it is closed?

**Comment by metalmatze** [comment]
Thanks!

**Comment by optimistic5** [comment]
Hi @metalmatze 
Could you please, update docker image, probably it is outdated from current master.

**Comment by metalmatze** [comment]
I need to cut another release for a docker image to be built and pushed. :)

**Comment by runningman84** [comment]
any news here?

**Comment by tcassaert** [comment]
While you're waiting for the release, you can easily add the template yourself with the `TEMPLATE_PATHS` environment variable. Create a directory with the template and mount it in your docker container, then set the value of the `TEMPLATE_PATHS` environment variable to that directory.

**Comment by nguyencuong1990** [comment]
hi, tcassaert
How to create template, please send me the guide to create template.

**Comment by tcassaert** [comment]
@nguyencuong1990 you create a file for your template, let's say `/opt/template.tmpl`. The content of that file is an adapted version of https://github.com/metalmatze/alertmanager-bot/blob/master/default.tmpl, according to your needs.

Then when you start the telegram-bot, you can pass an environment variable `TEMPLATE_PATHS=/opt/template.tmpl`.

**Comment by nguyencuong1990** [comment]
hi @tcassaert 
I was read https://github.com/metalmatze/alertmanager-bot/blob/master/default.tmpl
I want monitor my Vmware vcenter system. But only show FIRING on telegram group.
The rule apply of my case:
[https://gitlab.com/Danny_Pham/toivietblog/-/raw/master/Monitoring/Prometheus%20+%20Grafana/prometheus%20rules/vcenter.yml?inline=false](url)
image
Thanks for reply

**Comment by tcassaert** [comment]
@nguyencuong1990, in your rules file, your annotation `Summary` is written with a capital `S`, while the template is looking for a `summary` with a regular `s`. That's probably why it's not included in the alert message.

**Comment by nguyencuong1990** [comment]
hi @tcassaert ,
I was edited  my rule.yml file and restart all service, but nothing change.
image
thanks

**Comment by nguyencuong1990** [comment]
Hi @tcassaert 
After I change S to s on template notification send is true.
And add template.paths
--template.paths=/data/default.tmpl
image
Thank you so much!

**Pull request merged**
